### ISSUE TITLE
cannot restart engine

### ISSUE THREAD

**Issue by matthieu-robin** [julienmathis/centreon-docker#1]
Hello,

Unfortunately, we cannot restart engine. we got this error:
NOK (Could not write to file 'cgi.cfg' for monitoring engine 'Central'. Please add writing permissions for the webserver's user)

on the centreon-engine folder and centreon-broker.

**Comment by david-guenault** [comment]
c'est la génération de fichiers faites par clapi dans le docker file qui pète les droits. Pas grand chose a modifier dans le docker file pour mettre tout cela d'applomb

**Comment by julienmathis** [comment]
Merci David pour ce retour.

On va corriger cela !

**Comment by matthieu-robin** [comment]
Cool! merci beaucoup!
